### PR TITLE
Add images download repo info

### PR DESCRIPTION
**Pull request by m4u9**

### CODE REVIEW

**Comment by mcepl** [comment]
Which is exactly the problem: if I understand it correctly, @sysrich is completely overwhelmed with the work for his actual employer and tries to distance from the project. I am not doing that much better, but because I am actually using it as my daily driver, I am hesitantly taking over. If other people (you, @sfalken, anybody else?) would like to help I am all ears.

The option is either that I copy whole `home:RBrownSUSE:Greybeard` to my home project, or that (and it would be better) we create some shared space (`devel:microos:greybeard`?). Opinions?

**Comment by m4u9** [comment]
I think we should go for a neutral devel project such as `devel:microos:greybeard`. Ultimately it's @sysrich  decision, depending on whether he feels this can become something more official or keep on living as a home project

**Comment by m4u9** [comment]
@mcepl misread your message, if you're taking over from @sysrich  I am happy to continue contribute to this project wherever it goes. But yea an official devel project would probably be better. I have a plan to use this as base for a Xfce fork at one point as well

**Comment by mcepl** [comment]
Aside from the fixing the bugs I have filed so far, the only large project I think would be helpful to investigate is whether we should switch to `systemd-boot` and what would it actually mean for us. However, here I would appreciate help from somebody who actually knows a little bit more about the lower levels of the system, I am just a poor desktop/Python maintainer who knows nothing about it.

**Comment by m4u9** [comment]
systemd-boot is something I know very little about so probably can't be of much help here :(

**Pull request merged**
